<?php
$isLoggin = AuthHelper::checkSession();
$isAdmin = AuthHelper::verify();
?>
<h1 class= "text-center text-white">Categorias</h1>
<ul class="list-group">
    <?php foreach ($categorias as $categoria) { ?>   
        <li class="list-group-item">
            <b><a href="filtrocategoria/<?= $categoria->id_genero ?>" class="text-decoration-none text-dark"><?= $categoria->nombre_gen ?></a></b>
            <?php if($isAdmin=="administrador"){ ?>
            <form method="POST" action="editarCategoria/<?= $categoria->id_genero ?>">
                <input type="text" name="newCategory">
            </form>
            <?php } ?>
        </li>
    <?php } ?>
    <li class="list-group-item">
        <a href="games" class="text-decoration-none text-dark">Todos</a>
    </li>
</ul>


