<?php require 'templates/header.phtml'; ?>

<div class="AboutUs">
    <h1 class="text-center text-white">Sobre Nosotros</h1>
   <p class="text-center text-white">Buenos dias nosotros nos llamamos "GameShop" somos una pagina encargada de vender juegos a los mejores precios y tambien tenemos las mejores ofertas en los mismos!</p>
   <img class="mx-auto d-block" src="images/masterhacks_cofunders_reddit_fondo_videojuegos_blockchain.jpg">
</div> 

<?php require 'templates/footer.phtml' ?>
