<?php require 'templates/header.phtml'; ?>

<div>
    <ul class="list-group">
        <li class="list-group-item">
            <a href="showAddProducto" class="text-decoration-none text-dark">Agregar producto</a>
        </li>
        <li class="list-group-item">
            <a href="showAddCategoria" class="text-decoration-none text-dark">Agregar categoria</a>
        </li>
    </ul>
</div>

<?php require 'templates/footer.phtml' ?>