<?php require 'templates/header.phtml'; ?>

<h1 class= "text-center text-white">Categorias</h1>
<ul class="list-group">
    <?php foreach ($categorias as $categoria): ?>   
        <li class="list-group-item">
            <a href="categoria/<?= $categoria->id_genero ?>" class="text-decoration-none text-dark"><?= $categoria->nombre_gen ?></a>
            <?php if (AuthHelper::verify()): ?>
                <span>---</span>
                <button class="btn btn-success"><a class="text-white text-decoration-none" href="showUpdateCategoria/<?= $categoria->id_genero ?>">Editar </a></button>
                <span>---</span>
                <button class="btn btn-danger"><a class="text-white text-decoration-none" href="deleteCategoria/<?= $categoria->id_genero ?>" >Eliminar </a></button>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
    <li class="list-group-item">
        <a href="juegos" class="text-decoration-none text-dark">Todos</a>
    </li>
</ul>

<?php require 'templates/footer.phtml' ?>