<?php
require 'templates/header.phtml';
AuthHelper::checkSession();
if (isset($producto[0])):
    $Nombre = $producto[0]->nombre;
    $descripcion = $producto[0]->descripcion;
    $precio = $producto[0]->precio;
?>

<div class="container mt-4">
    <h1 class="display-4 text-white"><?= $Nombre; ?></h1>
    <h2 class="text-white"> precio: <?= $precio; ?> $</h2>
    <p class="mt-4 text-white"><?= $descripcion; ?></p>
</div>

<?php endif;

require 'templates/footer.phtml';

?>