<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?= HOME ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>GameShop</title>
</head>

<body class="bg-dark">

<header>
    <nav class="navbar navbar-expand-lg bg-light border-bottom border-danger">
        <div class="container-fluid">
            <a class="navbar-brand" href="home">GameShop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="juegos">Juegos</a>
                    </li>
                    <?php AuthHelper::init();
                    if (AuthHelper::verify()): ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="agregar">Agregar</a>
                        </li>
                    <?php endif; 
                    if (!isset($_SESSION['usuario'])): ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="login">Login</a>
                        </li>
                    <?php else: ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="logout">Logout</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
        </nav>
</header>

<main class="container mt-3">