<?php require 'templates/header.phtml'; ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <div class="form-group">
            <label class="text-white" for="usuario">Usuario</label>
            <input type="text" required class="form-control" id="usuario" name="usuario" aria-describedby="userHelp">
        </div>
        <div class="form-group">
            <label class="text-white" for="contrasenia">Contraseña</label>
            <input type="password" required class="form-control" id="contrasenia" name="contrasenia">
        </div>

        <?php if ($error): ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>