<?php require 'templates/header.phtml';
AuthHelper::checkSession();
?>

<h1 class= "text-center text-white">Juegos</h1>
<ul class="list-group">
    <?php foreach ($productos as $producto): ?>
        <li class="list-group-item">
            <a href="juegoUnico/<?= $producto->id_producto ?>" class="text-decoration-none text-dark"> <?= $producto->nombre ?> </a> 
        </li>
    <?php endforeach ?>
</ul>
<a href="home" class="btn btn-secondary"><-volver</a>

<?php require 'templates/footer.phtml' ?>