<?php require 'templates/header.phtml'; ?>

<h1 class= "text-center text-white">Juegos</h1>
<ul class="list-group">
    <?php foreach ($productos as $producto): ?>
        <li class="list-group-item">
            <a href="juegoUnico/<?= $producto->id_producto ?>" class="text-decoration-none text-dark"> <?= $producto->nombre ?> </a>
            <?php if (AuthHelper::verify()): ?>
                <span>---</span>
                <button class="btn btn-success"><a class="text-white text-decoration-none" href="showUpdateProducto/<?= $producto->id_producto ?>">Editar </a></button>
                <span>---</span>
                <button class="btn btn-danger"><a class="text-white text-decoration-none" href="deleteProducto/<?= $producto->id_producto ?>" >Eliminar </a></button>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ul>
<a href="home" class="btn btn-secondary"><-volver</a>

<?php require 'templates/footer.phtml' ?>